config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tweets
  root 'tweets#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  def self.get_latest_cricket_tweets
    #create a Twitter Search object
    client = Twitter::REST::Client.new do |config|
      config.consumer_key = 'QXjbeay9bh5xy1O710zJqV51i'
      config.consumer_secret = 'c2Proby2Ydctqw629hv8fO8hjUnpLSHFhyivxECjAirXwN9ehU'
      config.access_token = '2911021353-kaRkA5MflRqpAgq6O5ToWyBaFa7sbR4ZCh38IVW'
      config.access_token_secret = '0bCxw0jQr4rCo6RbFJCEQS8dtD7kDWN8kUemYAwiSr2xA'
    end
    client.search("cricket", result_type: "recent").take(100).collect do |tweetii|
      p "-----------#{tweetii.user.screen_name}: #{tweetii.text} :#{tweetii.created_at}  : #{tweetii.user.profile_image_url} : #{tweetii.user.id}------" 
      unless Tweet.exists?(['tweet_time = ? AND user_id = ?', "#{tweetii.created_at}", "#{tweetii.user.id}"])
        Tweet.create!(screen_name: "#{tweetii.user.screen_name}", tweet_content: "#{tweetii.text}", tweet_time: "#{tweetii.created_at}", profile_image: "#{tweetii.user.profile_image_url}", user_id: "#{tweetii.user.id}", tweet_id: "#{tweetii.id}")
      end
    end
  end

  def self.search(search)
    if search
      Tweet.where("tweet_content LIKE ?", "%#{search}%").order("created_at DESC")
    else
      Tweet.all.order("created_at DESC")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.search(params[:search]).paginate(page: params[:page], per_page: 20)
      respond_to do |format|
        format.html
        format.js
      end
  end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweetproject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/_tweet_partial.html.erb
<table>
  <tr>
    <th>Image</th>
    <th>Name</th>
    <th>Tweets</th>
  </tr>
 <%= will_paginate %>
  <% @tweets.each do |tweet| %>
    <tr>
      <td><%= image_tag image_url(tweet.profile_image) %></td>&nbsp;
      <td><%= tweet.screen_name %></td>&nbsp;
      <td><%= tweet.tweet_content %></td>&nbsp;
    </tr>
  <% end %>
</table>
<%= will_paginate @tweets %>

app/views/tweets/index.html.erb
<h1>Listing Tweets</h1>
<%= form_tag tweets_path, :method => 'get', remote: true do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Filter", :tweet_content => nil %>
  </p>

<% end %>

<div id="task-form">
 <%=render "tweet_partial" %>
</div>

app/views/tweets/index.js.erb
<%#binding.pry%>
$("#task-form").html("<%= escape_javascript(render("tweet_partial")) %>");